experiment_name: aramed_gec_deepseek

model:
  type: deepseek           # Model handler type: openai, huggingface, llama
  name: deepseek-chat             #model name 
  api_key: ""

cache_dir: /scratch/ca2627/huggingface

dataset:
  path: datasets/aramed_gec/gec_aramed.json    # Path to dataset JSON file
  instruction_path: datasets/aramed_mod/default.txt  # Path to instruction file 

task:
  type: aramed                # Task type: qa, summarization, etc.

output:
  predictions_path: results/predictions/aramed_gec_deepseek.csv
  metrics_path: results/metrics/aramed_gec_deepseek.json
