experiment_name: aramed_mod_claude

model:
  type: anthropic            #model handler type: openai, huggingface, llama
  name: claude-3-5-sonnet-20240620             #model name 

cache_dir: /scratch/ca2627/huggingface #modify to your own cache directory

dataset:
  path: datasets/aramed_mod/mod_aramed.json    #path to dataset JSON file
  instruction_path: datasets/aramed_mod/default.txt  #path to instruction file (default.txt)

task:
  type: aramed                #task type: qa, summarization, rag, etc...

output:
  predictions_path: results/predictions/aramed_mod_claude.csv #specify output pred file
  metrics_path: results/metrics/aramed_mod_claude.json  #specift output pred file

