experiment_name: aramed_mod_falcon 

model: 
  type: huggingface                              #model handler type: openai, huggingface, llama
  name: tiiuae/Falcon3-10B-Instruct       # Model name or identifier
  cache_dir: /scratch/ca2627/huggingface_cache  # Optional: Specify a custom cache directory


dataset:
  path: datasets/aramed_mod/mod_aramed.json    #path to dataset JSON file
  instruction_path: datasets/aramed/default.txt  #path to instruction file (default.txt)

task:
  type: aramed                #task type: qa, summarization, rag, etc...

output:
  predictions_path: results/predictions/aramed_mod_falcon.csv #specify output pred file
  metrics_path: results/metrics/aramed_mod_falcon.json  #specift output pred file

