experiment_name: aramed_mod_gemini

model:
  type: gemini            # Model handler type: openai, huggingface, llama
  name: gemini-1.5-pro            # Model name or identifier
  api_key: "AIzaSyDCvuvgs8IfQnj8TqlW_RQENI8A8ApPeyk"

cache_dir: /scratch/ca2627/huggingface #modify to your own cache directory

dataset:
  path: datasets/aramed_mod/mod_aramed.json    #path to dataset JSON file
  instruction_path: datasets/aramed_mod/default.txt  #path to instruction file (default.txt)

task:
  type: aramed                #task type: qa, summarization, rag, etc...

output:
  predictions_path: results/predictions/aramed_mod_gemini.csv #specify output pred file
  metrics_path: results/metrics/aramed_mod_gemini.json  #specift output pred file

