experiment_name: fib_closed_falcon 

model: 
  type: huggingface                              #model handler type: openai, huggingface, llama
  name: tiiuae/Falcon3-10B-Instruct       # Model name or identifier
  cache_dir: /scratch/ca2627/huggingface_cache  # Optional: Specify a custom cache directory


dataset:
  path: datasets/fib_closed/fib_ar.json    #path to dataset JSON file
  instruction_path: datasets/fib_closed/default.txt  #path to instruction file (default.txt)

task:
  type: fib_closed                #task type: qa, summarization, rag, etc...

output:
  predictions_path: results/predictions/fib_closed_falcon.csv #specify output pred file
  metrics_path: results/metrics/fib_closed_falcon.json  #specift output pred file

