experiment_name: fib_open_gemini

model:
  type: gemini            # Model handler type: openai, huggingface, llama
  name: gemini-1.5-pro            # Model name or identifier
  api_key: "AIzaSyDCvuvgs8IfQnj8TqlW_RQENI8A8ApPeyk"

cache_dir: /scratch/ca2627/huggingface #modify to your own cache directory

dataset:
  path: datasets/fib_open/fib_ar.json    #path to dataset JSON file
  instruction_path: datasets/fib_open/default.txt  #path to instruction file (default.txt)

task:
  type: fib_open                #task type: qa, summarization, rag, etc...

output:
  predictions_path: results/predictions/fib_open_gemini.csv #specify output pred file
  metrics_path: results/metrics/fib_open_gemini.json  #specift output pred file

