experiment_name: qa_claude 

model: 
  type: anthropic                              #model handler type: openai, huggingface, llama
  name: claude-3-5-sonnet-20240620             #model name 
  api_key: "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"

cache_dir: /scratch/ca2627/huggingface #modify to your own cache directory

dataset:
  path: datasets/qa/qa.json    #path to dataset JSON file
  instruction_path: datasets/qa/default.txt  #path to instruction file (default.txt)

task:
  type: qa                #task type: qa, summarization, rag, etc...

output:
  predictions_path: results/predictions/qa_claude.csv #specify output pred file
  metrics_path: results/metrics/qa_claude.json  #specift output pred file

