experiment_name: qa_llama3.1 

model:
  type: huggingface            # Model handler type: openai, huggingface, llama
  name: google/gemma-2b         # Model name or identifier

cache_dir: /scratch/ca2627/huggingface

dataset:
  path: datasets/qa/qa.json    # Path to dataset JSON file
  instruction_path: datasets/qa/default.txt  # Path to instruction file (default.txt)

task:
  type: qa                # Task type: qa, summarization, etc.

output:
  predictions_path: results/predictions/qa_gemma.csv
  metrics_path: results/metrics/qa_gemma.json
