experiment_name: aramed_mod_deepseek 

model: 
  type: deepseek                              #model handler type: openai, huggingface, llama
  name: deepseek-chat             #model name 
  api_key: ""
  
  cache_dir: /scratch/ca2627/huggingface_cache  # Optional: Specify a custom cache directory


dataset:
  path: datasets/aramed_mod/mod_aramed.json    #path to dataset JSON file
  instruction_path: datasets/aramed/default.txt  #path to instruction file (default.txt)

task:
  type: aramed                #task type: qa, summarization, rag, etc...

output:
  predictions_path: results/predictions/aramed_mod_deepseek.csv #specify output pred file
  metrics_path: results/metrics/aramed_mod_deepseek.json  #specift output pred file

