experiment_name: aramed_deepseek

model: 
  type: deepseek                              #model handler type: openai, huggingface, llama
  name: deepseek-chat             #model name 
  api_key: "sk-4e34a449f06447ac91df4039f41b7418"


dataset:
  path: datasets/aramed/aramed.json    #path to dataset JSON file
  instruction_path: datasets/aramed/default.txt  #path to instruction file (default.txt)

task:
  type: aramed                #task type: qa, summarization, rag, etc...

output:
  predictions_path: results/predictions/aramed_deepseek.csv #specify output pred file
  metrics_path: results/metrics/aramed_deepseek.json  #specift output pred file

