experiment_name: aramed_gec_gpt4 

model:
  type: openai            #model handler type: openai, huggingface, llama
  name: gpt-4             #model name 

cache_dir: /scratch/ca2627/huggingface #modify to your own cache directory

dataset:
  path: datasets/aramed_gec/gec_aramed.json    #path to dataset JSON file
  instruction_path: datasets/aramed/default.txt  #path to instruction file (default.txt)

task:
  type: aramed                #task type: qa, summarization, rag, etc...

output:
  predictions_path: results/predictions/aramed_gec_gpt4.csv #specify output pred file
  metrics_path: results/metrics/aramed_gec_gpt4.json  #specift output pred file

