experiment_name: aramed_llama3.1 

model:
  type: huggingface            # Model handler type: openai, huggingface, llama
  name: meta-llama/Llama-3.1-8B         # Model name or identifier

cache_dir: /scratch/ca2627/huggingface

dataset:
  path: datasets/aramed/aramed.json    # Path to dataset JSON file
  instruction_path: datasets/aramed/default.txt  # Path to instruction file (default.txt)

task:
  type: aramed                # Task type: qa, summarization, etc.

output:
  predictions_path: results/predictions/aramed_llama3.csv
  metrics_path: results/metrics/aramed_llama3.json
