experiment_name: fib_open_llama 

model: 
  type: huggingface            #model handler type: openai, huggingface, llama
  name: meta-llama/Llama-3.1-8B-Instruct       # Model name or identifier
  cache_dir: /scratch/ca2627/huggingface_cache  # Optional: Specify a custom cache directory


dataset:
  path: datasets/fib_open/fib_ar.json    #path to dataset JSON file
  instruction_path: datasets/fib_open/default.txt  #path to instruction file (default.txt)

task:
  type: fib_open                #task type: qa, summarization, rag, etc...

output:
  predictions_path: results/predictions/fib_open_llama.csv #specify output pred file
  metrics_path: results/metrics/fib_open_llama.json  #specift output pred file

