experiment_name: fib_closed_jais

model:
  type: huggingface           #model handler type: openai, huggingface, llama
  name: inceptionai/jais-13b-chat            #model name 

cache_dir: /scratch/ca2627/huggingface #modify to your own cache directory

dataset:
  path: datasets/fib_closed/fib_ar.json    #path to dataset JSON file
  instruction_path: datasets/fib_closed/default.txt  #path to instruction file (default.txt)

task:
  type: fib_closed                #task type: qa, summarization, rag, etc...

output:
  predictions_path: results/predictions/fib_en_jais.csv #specify output pred file
  metrics_path: results/metrics/fib_en_jais.json  #specift output pred file

