experiment_name: qa_medgemma

model:
  type: medgemma            # Model handler type: openai, huggingface, llama
  name: google/medgemma-27b-text-it            # Model name or identifier

dataset:
  path: datasets/qa/qa.json    # Path to dataset JSON file
  instruction_path: datasets/qa/default.txt  # Path to instruction file (default.txt)

task:
  type: qa                # Task type: qa, summarization, etc.

output:
  predictions_path: results/predictions/qa_medgemma.csv
  metrics_path: results/metrics/qa_medgemma.json